<?php

namespace App\Entity;

use App\Entity\Enum\CartStatus;
use App\Entity\Impl\AbstractEntity;
use App\Repository\CartRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity(repositoryClass: CartRepository::class)]
class Cart extends AbstractEntity
{
    #[ORM\Id]
    #[ORM\Column(type: UuidType::NAME, unique: true)]
    private Uuid $id;

    #[ORM\Column(enumType: CartStatus::class)]
    private CartStatus $status = CartStatus::Pending;

    /**
     * @var Collection<int, CartItem>
     */
    #[ORM\OneToMany(
        mappedBy: 'cart',
        targetEntity: CartItem::class,
        cascade: ['persist'],
        orphanRemoval: false,
    )]
    private Collection $items;

    /**
     * Builds an empty pending cart with a time-ordered UUID, generated by the entity itself.
     */
    public function __construct()
    {
        $this->id = Uuid::v7();
        $this->items = new ArrayCollection();
    }

    public function addItem(CartItem $item): static{
        $this->items->add($item);
        return $this;
    }
}
