<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\QueryParameter;
use App\Dto\City\CityListOutput;
use App\Entity\Impl\AbstractEntity;
use App\Repository\CityRepository;
use App\State\City\CityCollectionProvider;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity(repositoryClass: CityRepository::class)]
#[ApiResource(operations: [
    new GetCollection(
        uriTemplate: '/cities',
        provider: CityCollectionProvider::class,
        output: CityListOutput::class,
        // le contrat ne déclare pas de pagination sur cette liste
        paginationEnabled: false,
        // les deux paramètres du contrat, avec leur schéma : la validation en découle
        parameters: [
            'q' => new QueryParameter(
                description: 'Filtre textuel sur le nom de la ville. Insensible à la casse et aux accents.',
                schema: ['type' => 'string'],
            ),
            'limit' => new QueryParameter(
                description: 'Nombre maximum de villes retournées.',
                schema: [
                    'type' => 'integer',
                    'minimum' => 1,
                    'maximum' => 100,
                    'default' => 20,
                ],
            ),
        ],
    ),
])]
class City extends AbstractEntity
{
    #[ORM\Id]
    #[ORM\Column(type: UuidType::NAME, unique: true)]
    private Uuid $id;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    /**
     * Builds a city with a time-ordered UUID, generated by the entity itself.
     */
    public function __construct()
    {
        $this->id = Uuid::v7();
    }

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }
}
