<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\GetCollection;
use App\Dto\Ticket\TicketListOutput;
use App\Entity\Impl\AbstractEntity;
use App\Repository\TicketRepository;
use App\State\Ticket\TicketCollectionProvider;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity(repositoryClass: TicketRepository::class)]
#[ApiResource(operations: [
    new GetCollection(
        uriTemplate: '/tickets',
        output: TicketListOutput::class,
        provider: TicketCollectionProvider::class,
        security: "is_granted('ROLE_USER')",
    ),
])]
class Ticket extends AbstractEntity
{
    #[ORM\Id]
    #[ORM\Column(type: UuidType::NAME, unique: true)]
    private Uuid $id;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Trip $trip = null;

    // dans un seul sens : aucune opération ne demande au panier ses billets, Cart ne change pas
    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Cart $cart = null;

    /**
     * Price paid for this seat, in cents, copied from the trip at payment time.
     */
    // une copie, pas une lecture : le prix acquitté ne suit plus celui du lancer
    #[ORM\Column]
    private ?int $price = null;

    /**
     * Builds a ticket with a time-ordered UUID, generated by the entity itself.
     */
    public function __construct()
    {
        $this->id = Uuid::v7();
    }

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function getTrip(): ?Trip
    {
        return $this->trip;
    }

    public function setTrip(Trip $trip): static
    {
        $this->trip = $trip;

        return $this;
    }

    public function getCart(): ?Cart
    {
        return $this->cart;
    }

    public function setCart(Cart $cart): static
    {
        $this->cart = $cart;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }
}
