<?php

namespace App\Entity;

use App\Entity\Enum\CatapultModel;
use App\Entity\Impl\AbstractEntity;
use App\Repository\TripRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity(repositoryClass: TripRepository::class)]
class Trip extends AbstractEntity
{
    #[ORM\Id]
    #[ORM\Column(type: UuidType::NAME, unique: true)]
    private Uuid $id;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(name: 'origin_city_id', nullable: false)]
    private ?City $origin = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(name: 'destination_city_id', nullable: false)]
    private ?City $destination = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $departureAt = null;

    /**
     * Flight duration, in minutes.
     */
    #[ORM\Column]
    private ?int $duration = null;

    /**
     * Seat price, in cents.
     */
    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column(enumType: CatapultModel::class)]
    private ?CatapultModel $catapultModel = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $boardingInfo = null;

    /**
     * Builds a trip with a time-ordered UUID, generated by the entity itself.
     */
    public function __construct()
    {
        $this->id = Uuid::v7();
    }
}
